---
- name: "Render template for DataDog config file (no_log)"
  ansible.builtin.template:
    src: datadog.yaml.j2
    dest: "{{ datadog_cfg_file }}"
    mode: "0600"
    owner: "{{ datadog_owner }}"
    group: "{{ datadog_group }}"
  when: datadog_state == "present"
  notify: "{{ datadog_handler }}"
  no_log: true
  become: true
  tags: [ct-datadog]
...
