---
# --------------------------------

- name: 'include common tasks'
  include_tasks: common.yml
  tags:
  - ct-datadog

- name: 'include {{ct_distro}} tasks'
  include_tasks: setup_{{ct_distro}}.yml
  when:
  - ct_distro == 'ubuntu' or ct_distro == 'redhat'
  tags:
  - ct-datadog

# --------------------------------
...
