---
# --------------------------------

- name: 'include common tasks'
  include_tasks: common.yml
  tags:
  - ct-datadog

- name: 'include {{ct_family}} tasks'
  include_tasks: setup_{{ct_family}}.yml
  when:
  - ct_family == 'debian' or ct_family == 'redhat'
  tags:
  - ct-datadog

# --------------------------------
...
