---
# --------------------------------

- name: "Include {{ ct_family }} tasks"
  ansible.builtin.include_tasks: setup-{{ ct_family }}.yml
  when:
  - ct_family == "debian" or ct_family == "redhat"
  tags: [ct-datadog]

- name: "Install config file"
  ansible.builtin.include_tasks: install_config.yml
  tags: [ct-datadog]

- name: "Include post install tasks"
  ansible.builtin.include_tasks: post_tasks.yml
  tags: [ct-datadog]

# --------------------------------
...
