---
- name: "Install repo source for {{ ct_family }}"
  ansible.builtin.template:
    src: datadog.repo.j2
    dest: /etc/yum.repos.d/datadog.repo
    mode: "0644"
    owner: root
    group: root
  register: reg_repo
  become: true
  tags: [ct-datadog]

- name: "Install datadog package for {{ ct_family }}"
  ansible.builtin.yum:
    name: datadog-agent
    state: "{{ datadog_state }}"
    enablerepo: datadog
    disablerepo: "*"
    update_cache: "{{ reg_repo is changed }}"
  become: true
  tags: [ct-datadog]
...
