---
# --------------------------------

- name: "Override service name for Ubuntu 14"
  ansible.builtin.set_fact:
    datadog_handler: Handler_Restart_Datadog_Old
    datadog_svc_name: datadog-agent
  when:
  - ct_distro == "ubuntu"
  - ct_distro_major|int == 14
  tags: [ct-datadog]

- name: "Update package cache and install pre-requisites"
  ansible.builtin.apt:
    name: "{{ datadog_pkg_dependencies }}"
    state: present
    update_cache: false
  become: true
  tags: [ct-datadog]

# --------------------------------

- name: "Add repo keys"
  ansible.builtin.apt_key:
    keyring: "{{ datadog_keyring }}"
    state: present
    validate_certs: true
    url: "{{ item }}"
  loop: "{{ datadog_repo_keys }}"
  become: true
  tags: ["ct-envoy"]

- name: "Add public key of DataDog repo"
  ansible.builtin.apt_key:
    id: "{{ datadog_pubkey_id }}"
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    validate_certs: true
  when: false  # deprecated 10 March 2023
  become: true
  tags: [ct-datadog]

- name: "Add DataDog repository"
  ansible.builtin.apt_repository:
    filename: datadog
    repo: "deb [signed-by={{ datadog_keyring }}] https://apt.datadoghq.com/ stable {{ datadog_agent_version }}"
    state: present
    update_cache: true
    validate_certs: true
  become: true
  tags: [ct-datadog]

# --------------------------------

- name: "Install DataDog agent"
  ansible.builtin.apt:
    name: "{{ datadog_pkg_names }}"
    state: "{{ datadog_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: [ct-datadog]

- name: "Render template for DataDog config file (no_log)"
  ansible.builtin.template:
    dest: "{{ datadog_cfg_file }}"
    group: "{{ datadog_group }}"
    mode: "0600"
    owner: "{{ datadog_owner }}"
    src: datadog.yaml.j2
  when: datadog_state == "present"
  no_log: true
  notify: "{{ datadog_handler }}"
  become: true
  tags: [ct-datadog]

# --------------------------------

- name: "Configure DataDog service status={{ datadog_agent_status }} enabled={{ datadog_agent_enabled | ternary(false, true) }}"
  ansible.builtin.systemd:
    enabled: "{{ datadog_agent_enabled }}"
    masked: "{{ datadog_agent_enabled | ternary(false, true) }}"
    name: "{{ item }}"
    state: "{{ datadog_agent_status }}"
  become: true
  with_items:
  - "{{ datadog_svc_name }}"
  - "datadog-agent-process"
  - "datadog-agent-trace"
  tags: [ct-datadog]

# --------------------------------
...
