---
- name: "Handler_Restart_Datadog"
  ansible.builtin.systemd:
    state: restarted
    name: "{{ datadog_svc_name }}"
  become: true

- name: "Handler_Restart_Datadog_Old"  # alt handler for Ubuntu 14
  ansible.builtin.shell: (/opt/datadog-agent/bin/agent/agent stop) && (/opt/datadog-agent/bin/agent/agent run > /var/log/datadog/agent.log 2>&1 &)
  become: true
  become_user: "{{ datadog_owner }}"
  when: false
  tags: skip_ansible_lint
...
